### ISSUE TITLE
new SN2016ccj redshift

### ISSUE THREAD

**Issue by pbrown801** [astrocatalogs/sne-internal#155]
The host galaxy redshift of SN2016ccj can be updated to 0.041376 based on Foley et al. 2018   https://ui.adsabs.harvard.edu/abs/2018MNRAS.475..193F/abstract

**Comment by guillochon** [comment]
Addressed in https://github.com/astrocatalogs/sne-internal/pull/157.

**Comment by pbrown801** [comment]
I don't see this update on the website yet.  I'm wanting to run mosfit on this object with the correct redshift.  Thanks!

**Comment by guillochon** [comment]
Turns out I had a syntax error in the file and that prevented the updated from appearing. It should appear in a few days.

You can manually specify the redshift on the command line and override the OSC's value temporarily.
